package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.DateSerializer;

/**
 * AccessList generated by hbm2java
 */
@Entity
@Table(name = "ACCESS_LIST")
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE, region="accessList")
public class AccessList implements java.io.Serializable {

	private Long accessId;
	private String accessName;
	private String urlName;
	private Long createdBy;
	private Long modifiedBy;
	private Long deletedBy;
	private Date createdDate;
	private Date modifiedDate;
	private Date deletedDate;
	private String deleteFlag;
	private Set<RoleAccessRlns> roleAccessRlnses = new HashSet<RoleAccessRlns>(0);

	public AccessList() {
	}

	public AccessList(Long accessId) {
		this.accessId = accessId;
	}

	public AccessList(Long accessId, String accessName, String urlName,
			Long createdBy, Long modifiedBy, Long deletedBy,
			Date createdDate, Date modifiedDate, Date deletedDate,
			String deleteFlag, Set<RoleAccessRlns> roleAccessRlnses) {
		this.accessId = accessId;
		this.accessName = accessName;
		this.urlName = urlName;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.deletedBy = deletedBy;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.deletedDate = deletedDate;
		this.deleteFlag = deleteFlag;
		this.roleAccessRlnses = roleAccessRlnses;
	}

	@Id
	/*@SequenceGenerator(name="ACCESS_LIST_SEQ",sequenceName="ACCESS_LIST_SEQ")
	@GeneratedValue(generator="ACCESS_LIST_SEQ",strategy=GenerationType.AUTO)*/
	@Column(name = "ACCESS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getAccessId() {
		return this.accessId;
	}

	public void setAccessId(Long accessId) {
		this.accessId = accessId;
	}

	@Column(name = "ACCESS_NAME")
	public String getAccessName() {
		return this.accessName;
	}

	public void setAccessName(String accessName) {
		this.accessName = accessName;
	}

	@Column(name = "URL_NAME")
	public String getUrlName() {
		return this.urlName;
	}

	public void setUrlName(String urlName) {
		this.urlName = urlName;
	}

	@Column(name = "CREATED_BY", precision = 22, scale = 0)
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "MODIFIED_BY", precision = 22, scale = 0)
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "DELETED_BY", precision = 22, scale = 0)
	public Long getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(Long deletedBy) {
		this.deletedBy = deletedBy;
	}
	@JsonSerialize(using=DateSerializer.class)
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	@JsonSerialize(using=DateSerializer.class)
	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	@JsonSerialize(using=DateSerializer.class)
	@Temporal(TemporalType.DATE)
	@Column(name = "DELETED_DATE", length = 7)
	public Date getDeletedDate() {
		return this.deletedDate;
	}

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	@Column(name = "DELETE_FLAG", length = 1)
	public String getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accessList")
	public Set<RoleAccessRlns> getRoleAccessRlnses() {
		return this.roleAccessRlnses;
	}

	public void setRoleAccessRlnses(Set<RoleAccessRlns> roleAccessRlnses) {
		this.roleAccessRlnses = roleAccessRlnses;
	}

}
