package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AgentMst generated by hbm2java
 */
@Entity
@Table(name = "AGENT_MST", uniqueConstraints = @UniqueConstraint(columnNames = "OLD_AG_CODE"))
public class AgentMst implements java.io.Serializable {

	private Long agCode;
	private AgentMst agentMst;
	private StateMst stateMst;
	private JoinProdMst joinProdMst;
	private CampMst campMst;
	private WrkflwApprvMst wrkflwApprvMst;
	private RankMst rankMst;
	private String oldAgCode;
	private Long applNo;
	private Date applDate;
	private Date applSubmittedOn;
	private Long receiptId;
	private String phyReceiptNo;
	private String agName;
	private Long ageYrs;
	private Long ageMnth;
	private String gender;
	private Date dob;
	private Long locId;
	private String locFlag;
	private Long phaseId;
	private String add1;
	private String add2;
	private String add3;
	private String city;
	private String village;
	private Long pin;
	private String telNo;
	private Long mobile;
	private String email;
	private String guardian;
	private String foodPref;
	private String bldGrp;
	private String disease;
	private String occup;
	private String pan;
	private String eduQual;
	private Date doj;
	private String phyKitRcptNo;
	private String finYr;
	private String nameChangeFlag;
	private String docEviDtls;
	private String agPayMode;
	private Long userId;
	private Date dateTime;
	private String panVerified;
	private String unit;
	private Long introRankId;
	private String agNomName;
	private String agNomRlns;
	private Long modifiedBy;
	private Date modifiedDate;
	private Long approvalby;
	private Date approvalDate;
	private String processFlag;
	private String approvalFlag;
	private Set<LicOblApplicationMst> licOblApplicationMsts = new HashSet<LicOblApplicationMst>(0);
	private Set<AgentMst> agentMsts = new HashSet<AgentMst>(0);
	private Set<AgentRlns> agentRlnses = new HashSet<AgentRlns>(0);
	private Set<LicBusinessTxn> licBusinessTxns = new HashSet<LicBusinessTxn>(0);
	private List<LicPolicyDtls> licPolicyDtlses = new ArrayList<LicPolicyDtls>();
	private List<LicPolicyMst> licPolicyMsts = new ArrayList<LicPolicyMst>();
	private List<GenericBusinessTxn> genericBusinessTxns = new ArrayList<GenericBusinessTxn>();

	public AgentMst() {
	}

	public AgentMst(Long agCode, Date doj, String finYr, String unit) {
		this.agCode = agCode;
		this.doj = doj;
		this.finYr = finYr;
		this.unit = unit;
	}

	

	@Id
	@Column(name = "AG_CODE", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getAgCode() {
		return this.agCode;
	}

	public void setAgCode(Long agCode) {
		this.agCode = agCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INTRO_CODE")
	public AgentMst getAgentMst() {
		return this.agentMst;
	}

	public void setAgentMst(AgentMst agentMst) {
		this.agentMst = agentMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_ID")
	public StateMst getStateMst() {
		return this.stateMst;
	}

	public void setStateMst(StateMst stateMst) {
		this.stateMst = stateMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOIN_PROD_ID")
	public JoinProdMst getJoinProdMst() {
		return this.joinProdMst;
	}

	public void setJoinProdMst(JoinProdMst joinProdMst) {
		this.joinProdMst = joinProdMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAMP_ID")
	public CampMst getCampMst() {
		return this.campMst;
	}

	public void setCampMst(CampMst campMst) {
		this.campMst = campMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WRKFLW_ID")
	public WrkflwApprvMst getWrkflwApprvMst() {
		return this.wrkflwApprvMst;
	}

	public void setWrkflwApprvMst(WrkflwApprvMst wrkflwApprvMst) {
		this.wrkflwApprvMst = wrkflwApprvMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RANK_ID")
	public RankMst getRankMst() {
		return this.rankMst;
	}

	public void setRankMst(RankMst rankMst) {
		this.rankMst = rankMst;
	}

	@Column(name = "OLD_AG_CODE", unique = true, length = 20)
	public String getOldAgCode() {
		return this.oldAgCode;
	}

	public void setOldAgCode(String oldAgCode) {
		this.oldAgCode = oldAgCode;
	}

	@Column(name = "APPL_NO", precision = 22, scale = 0)
	public Long getApplNo() {
		return this.applNo;
	}

	public void setApplNo(Long applNo) {
		this.applNo = applNo;
	}

	@Column(name = "APPL_DATE")
	public Date getApplDate() {
		return this.applDate;
	}

	public void setApplDate(Date applDate) {
		this.applDate = applDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APPL_SUBMITTED_ON", length = 7)
	public Date getApplSubmittedOn() {
		return this.applSubmittedOn;
	}

	public void setApplSubmittedOn(Date applSubmittedOn) {
		this.applSubmittedOn = applSubmittedOn;
	}

	@Column(name = "RECEIPT_ID", precision = 22, scale = 0)
	public Long getReceiptId() {
		return this.receiptId;
	}

	public void setReceiptId(Long receiptId) {
		this.receiptId = receiptId;
	}

	@Column(name = "PHY_RECEIPT_NO", length = 20)
	public String getPhyReceiptNo() {
		return this.phyReceiptNo;
	}

	public void setPhyReceiptNo(String phyReceiptNo) {
		this.phyReceiptNo = phyReceiptNo;
	}

	@Column(name = "AG_NAME", length = 50)
	public String getAgName() {
		return this.agName;
	}

	public void setAgName(String agName) {
		this.agName = agName;
	}

	@Column(name = "AGE_YRS", precision = 22, scale = 0)
	public Long getAgeYrs() {
		return this.ageYrs;
	}

	public void setAgeYrs(Long ageYrs) {
		this.ageYrs = ageYrs;
	}

	@Column(name = "AGE_MNTH", precision = 22, scale = 0)
	public Long getAgeMnth() {
		return this.ageMnth;
	}

	public void setAgeMnth(Long ageMnth) {
		this.ageMnth = ageMnth;
	}

	@Column(name = "GENDER", length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 7)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "LOC_ID", precision = 22, scale = 0)
	public Long getLocId() {
		return this.locId;
	}

	public void setLocId(Long locId) {
		this.locId = locId;
	}

	@Column(name = "LOC_FLAG", length = 1)
	public String getLocFlag() {
		return this.locFlag;
	}

	public void setLocFlag(String locFlag) {
		this.locFlag = locFlag;
	}

	@Column(name = "PHASE_ID", precision = 22, scale = 0)
	public Long getPhaseId() {
		return this.phaseId;
	}

	public void setPhaseId(Long phaseId) {
		this.phaseId = phaseId;
	}

	@Column(name = "ADD_1", length = 500)
	public String getAdd1() {
		return this.add1;
	}

	public void setAdd1(String add1) {
		this.add1 = add1;
	}

	@Column(name = "ADD_2", length = 50)
	public String getAdd2() {
		return this.add2;
	}

	public void setAdd2(String add2) {
		this.add2 = add2;
	}

	@Column(name = "ADD_3", length = 50)
	public String getAdd3() {
		return this.add3;
	}

	public void setAdd3(String add3) {
		this.add3 = add3;
	}

	@Column(name = "CITY", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "VILLAGE", length = 20)
	public String getVillage() {
		return this.village;
	}

	public void setVillage(String village) {
		this.village = village;
	}

	@Column(name = "PIN", precision = 22, scale = 0)
	public Long getPin() {
		return this.pin;
	}

	public void setPin(Long pin) {
		this.pin = pin;
	}

	@Column(name = "TEL_NO", length = 50)
	public String getTelNo() {
		return this.telNo;
	}

	public void setTelNo(String telNo) {
		this.telNo = telNo;
	}

	@Column(name = "MOBILE", precision = 22, scale = 0)
	public Long getMobile() {
		return this.mobile;
	}

	public void setMobile(Long mobile) {
		this.mobile = mobile;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "GUARDIAN", length = 50)
	public String getGuardian() {
		return this.guardian;
	}

	public void setGuardian(String guardian) {
		this.guardian = guardian;
	}

	@Column(name = "FOOD_PREF", length = 10)
	public String getFoodPref() {
		return this.foodPref;
	}

	public void setFoodPref(String foodPref) {
		this.foodPref = foodPref;
	}

	@Column(name = "BLD_GRP", length = 3)
	public String getBldGrp() {
		return this.bldGrp;
	}

	public void setBldGrp(String bldGrp) {
		this.bldGrp = bldGrp;
	}

	@Column(name = "DISEASE", length = 30)
	public String getDisease() {
		return this.disease;
	}

	public void setDisease(String disease) {
		this.disease = disease;
	}

	@Column(name = "OCCUP", length = 20)
	public String getOccup() {
		return this.occup;
	}

	public void setOccup(String occup) {
		this.occup = occup;
	}

	@Column(name = "PAN", length = 10)
	public String getPan() {
		return this.pan;
	}

	public void setPan(String pan) {
		this.pan = pan;
	}

	@Column(name = "EDU_QUAL", length = 30)
	public String getEduQual() {
		return this.eduQual;
	}

	public void setEduQual(String eduQual) {
		this.eduQual = eduQual;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOJ", nullable = false, length = 7)
	public Date getDoj() {
		return this.doj;
	}

	public void setDoj(Date doj) {
		this.doj = doj;
	}

	@Column(name = "PHY_KIT_RCPT_NO", length = 10)
	public String getPhyKitRcptNo() {
		return this.phyKitRcptNo;
	}

	public void setPhyKitRcptNo(String phyKitRcptNo) {
		this.phyKitRcptNo = phyKitRcptNo;
	}

	@Column(name = "FIN_YR", nullable = false, length = 9)
	public String getFinYr() {
		return this.finYr;
	}

	public void setFinYr(String finYr) {
		this.finYr = finYr;
	}

	@Column(name = "NAME_CHANGE_FLAG", length = 1)
	public String getNameChangeFlag() {
		return this.nameChangeFlag;
	}

	public void setNameChangeFlag(String nameChangeFlag) {
		this.nameChangeFlag = nameChangeFlag;
	}

	@Column(name = "DOC_EVI_DTLS", length = 500)
	public String getDocEviDtls() {
		return this.docEviDtls;
	}

	public void setDocEviDtls(String docEviDtls) {
		this.docEviDtls = docEviDtls;
	}

	@Column(name = "AG_PAY_MODE", length = 1)
	public String getAgPayMode() {
		return this.agPayMode;
	}

	public void setAgPayMode(String agPayMode) {
		this.agPayMode = agPayMode;
	}

	

	
	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "PAN_VERIFIED", length = 1)
	public String getPanVerified() {
		return this.panVerified;
	}

	public void setPanVerified(String panVerified) {
		this.panVerified = panVerified;
	}

	@Column(name = "UNIT", nullable = false, length = 50)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "INTRO_RANK_ID", precision = 22, scale = 0)
	public Long getIntroRankId() {
		return this.introRankId;
	}

	public void setIntroRankId(Long introRankId) {
		this.introRankId = introRankId;
	}

	@Column(name = "AG_NOM_NAME", length = 50)
	public String getAgNomName() {
		return this.agNomName;
	}

	public void setAgNomName(String agNomName) {
		this.agNomName = agNomName;
	}

	@Column(name = "AG_NOM_RLNS", length = 20)
	public String getAgNomRlns() {
		return this.agNomRlns;
	}

	public void setAgNomRlns(String agNomRlns) {
		this.agNomRlns = agNomRlns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agentMst")
	public Set<LicOblApplicationMst> getLicOblApplicationMsts() {
		return this.licOblApplicationMsts;
	}

	public void setLicOblApplicationMsts(
			Set<LicOblApplicationMst> licOblApplicationMsts) {
		this.licOblApplicationMsts = licOblApplicationMsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agentMst")
	public Set<AgentMst> getAgentMsts() {
		return this.agentMsts;
	}

	public void setAgentMsts(Set<AgentMst> agentMsts) {
		this.agentMsts = agentMsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agentMst")
	public Set<AgentRlns> getAgentRlnses() {
		return this.agentRlnses;
	}

	public void setAgentRlnses(Set<AgentRlns> agentRlnses) {
		this.agentRlnses = agentRlnses;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agentMst")
	public Set<LicBusinessTxn> getLicBusinessTxns() {
		return licBusinessTxns;
	}

	public void setLicBusinessTxns(Set<LicBusinessTxn> licBusinessTxns) {
		this.licBusinessTxns = licBusinessTxns;
	}
	@Column(name = "MODIFIED_BY", precision = 22, scale = 0)
	public Long getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	@Column(name = "APPROVAL_BY", precision = 22, scale = 0)
	public Long getApprovalby() {
		return approvalby;
	}

	public void setApprovalby(Long approvalby) {
		this.approvalby = approvalby;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "APPROVAL_DATE", length = 7)
	public Date getApprovalDate() {
		return approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}
	@Column(name = "PROCESS_FLAG", length = 1)
	public String getProcessFlag() {
		return processFlag;
	}

	public void setProcessFlag(String processFlag) {
		this.processFlag = processFlag;
	}
	@Column(name = "APPROVAL_FLAG", length = 1)
	public String getApprovalFlag() {
		return approvalFlag;
	}

	public void setApprovalFlag(String approvalFlag) {
		this.approvalFlag = approvalFlag;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agentMst")
	public List<LicPolicyDtls> getLicPolicyDtlses() {
		return licPolicyDtlses;
	}

	public void setLicPolicyDtlses(List<LicPolicyDtls> licPolicyDtlses) {
		this.licPolicyDtlses = licPolicyDtlses;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agentMst")
	public List<LicPolicyMst> getLicPolicyMsts() {
		return licPolicyMsts;
	}

	public void setLicPolicyMsts(List<LicPolicyMst> licPolicyMsts) {
		this.licPolicyMsts = licPolicyMsts;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agentMst")
	public List<GenericBusinessTxn> getGenericBusinessTxns() {
		return genericBusinessTxns;
	}

	public void setGenericBusinessTxns(List<GenericBusinessTxn> genericBusinessTxns) {
		this.genericBusinessTxns = genericBusinessTxns;
	}

}
