package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gtfs.action.LicPrintReceiptAction;

/**
 * BranchMst generated by hbm2java
 */
@Entity
@Table(name = "BRANCH_MST")
public class BranchMst implements java.io.Serializable {

	private Long branchId;
	private DivisionMst divisionMstByPrntDivIdBns;
	private DivisionMst divisionMstByPrntDivIdOps;
	private StateMst stateMst;
	private String branchName;
	private String branchAbbr;
	private String branchCode;
	private String addr1;
	private String addr2;
	private String addr3;
	private String city;
	private Long pin;
	private String phone;
	private String mobile;
	private String email;
	private String activeFlag;
	private Long trnfLocation;
	private String remarks;
	private Long userId;
	private Date dateTime;
	private String licHubType;
	private Set<UserMst> userMsts = new HashSet<UserMst>(0);
	private Set<LicOblChecklist> licOblChecklists = new HashSet<LicOblChecklist>(0);
	private Set<LicOblApplicationMst> licOblApplicationMsts = new HashSet<LicOblApplicationMst>(0);
	private Set<CampMst> campMsts = new HashSet<CampMst>(0);
	
	private List<LicBranchHubMap> LicBranchHubMaps = new ArrayList<LicBranchHubMap>(0);
	
	private List<PrintRcptMst> printRcptMsts = new ArrayList<PrintRcptMst>();
	private List<LicPolicyDtls> licPolicyDtlses = new ArrayList<LicPolicyDtls>();
	private List<GenericBusinessTxn> genericBusinessTxns = new ArrayList<GenericBusinessTxn>();
	
	public BranchMst() {
	}

	public BranchMst(Long branchId) {
		this.branchId = branchId;
	}

	public BranchMst(Long branchId,
			DivisionMst divisionMstByPrntDivIdBns,
			DivisionMst divisionMstByPrntDivIdOps, StateMst stateMst,
			String branchName, String branchAbbr, String branchCode,
			String addr1, String addr2, String addr3, String city,
			Long pin, String phone, String mobile, String email,
			String activeFlag, Long trnfLocation, String remarks,
			Long userId, Date dateTime, String licHubType,
			Set<UserMst> userMsts, Set<LicOblChecklist> licOblChecklists,
			Set<LicOblApplicationMst> licOblApplicationMsts,
			Set<CampMst> campMsts) {
		this.branchId = branchId;
		this.divisionMstByPrntDivIdBns = divisionMstByPrntDivIdBns;
		this.divisionMstByPrntDivIdOps = divisionMstByPrntDivIdOps;
		this.stateMst = stateMst;
		this.branchName = branchName;
		this.branchAbbr = branchAbbr;
		this.branchCode = branchCode;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.addr3 = addr3;
		this.city = city;
		this.pin = pin;
		this.phone = phone;
		this.mobile = mobile;
		this.email = email;
		this.activeFlag = activeFlag;
		this.trnfLocation = trnfLocation;
		this.remarks = remarks;
		this.userId = userId;
		this.dateTime = dateTime;
		this.licHubType = licHubType;
		this.userMsts = userMsts;
		this.licOblChecklists = licOblChecklists;
		this.licOblApplicationMsts = licOblApplicationMsts;
		this.campMsts = campMsts;
	}

	@Id
	@Column(name = "BRANCH_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Long branchId) {
		this.branchId = branchId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRNT_DIV_ID_BNS")
	public DivisionMst getDivisionMstByPrntDivIdBns() {
		return this.divisionMstByPrntDivIdBns;
	}

	public void setDivisionMstByPrntDivIdBns(
			DivisionMst divisionMstByPrntDivIdBns) {
		this.divisionMstByPrntDivIdBns = divisionMstByPrntDivIdBns;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRNT_DIV_ID_OPS")
	public DivisionMst getDivisionMstByPrntDivIdOps() {
		return this.divisionMstByPrntDivIdOps;
	}

	public void setDivisionMstByPrntDivIdOps(
			DivisionMst divisionMstByPrntDivIdOps) {
		this.divisionMstByPrntDivIdOps = divisionMstByPrntDivIdOps;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_ID")
	public StateMst getStateMst() {
		return this.stateMst;
	}

	public void setStateMst(StateMst stateMst) {
		this.stateMst = stateMst;
	}

	@Column(name = "BRANCH_NAME", length = 20)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "BRANCH_ABBR", length = 4)
	public String getBranchAbbr() {
		return this.branchAbbr;
	}

	public void setBranchAbbr(String branchAbbr) {
		this.branchAbbr = branchAbbr;
	}

	@Column(name = "BRANCH_CODE", length = 4)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "ADDR_1", length = 250)
	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	@Column(name = "ADDR_2", length = 90)
	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "ADDR_3", length = 30)
	public String getAddr3() {
		return this.addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	@Column(name = "CITY", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "PIN", precision = 22, scale = 0)
	public Long getPin() {
		return this.pin;
	}

	public void setPin(Long pin) {
		this.pin = pin;
	}

	@Column(name = "PHONE", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "MOBILE", length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ACTIVE_FLAG", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "TRNF_LOCATION", precision = 22, scale = 0)
	public Long getTrnfLocation() {
		return this.trnfLocation;
	}

	public void setTrnfLocation(Long trnfLocation) {
		this.trnfLocation = trnfLocation;
	}

	@Column(name = "REMARKS", length = 20)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "LIC_HUB_TYPE", length = 20)
	public String getLicHubType() {
		return this.licHubType;
	}

	public void setLicHubType(String licHubType) {
		this.licHubType = licHubType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchMst")
	public Set<UserMst> getUserMsts() {
		return this.userMsts;
	}

	public void setUserMsts(Set<UserMst> userMsts) {
		this.userMsts = userMsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchMst")
	public Set<LicOblChecklist> getLicOblChecklists() {
		return this.licOblChecklists;
	}

	public void setLicOblChecklists(Set<LicOblChecklist> licOblChecklists) {
		this.licOblChecklists = licOblChecklists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchMst")
	public Set<LicOblApplicationMst> getLicOblApplicationMsts() {
		return this.licOblApplicationMsts;
	}

	public void setLicOblApplicationMsts(
			Set<LicOblApplicationMst> licOblApplicationMsts) {
		this.licOblApplicationMsts = licOblApplicationMsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchMst")
	public Set<CampMst> getCampMsts() {
		return this.campMsts;
	}

	public void setCampMsts(Set<CampMst> campMsts) {
		this.campMsts = campMsts;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchMst")
	public List<LicBranchHubMap> getLicBranchHubMaps() {
		return LicBranchHubMaps;
	}

	public void setLicBranchHubMaps(List<LicBranchHubMap> licBranchHubMaps) {
		LicBranchHubMaps = licBranchHubMaps;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchMst")
	public List<PrintRcptMst> getPrintRcptMsts() {
		return printRcptMsts;
	}

	public void setPrintRcptMsts(List<PrintRcptMst> printRcptMsts) {
		this.printRcptMsts = printRcptMsts;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchMst")
	public List<LicPolicyDtls> getLicPolicyDtlses() {
		return licPolicyDtlses;
	}

	public void setLicPolicyDtlses(List<LicPolicyDtls> licPolicyDtlses) {
		this.licPolicyDtlses = licPolicyDtlses;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchMst")
	public List<GenericBusinessTxn> getGenericBusinessTxns() {
		return genericBusinessTxns;
	}

	public void setGenericBusinessTxns(List<GenericBusinessTxn> genericBusinessTxns) {
		this.genericBusinessTxns = genericBusinessTxns;
	}

	@Override
	public boolean equals(Object obj) {
		BranchMst branchMst=(BranchMst) obj;
		return this.getBranchId().equals(branchMst.getBranchId());
	}
}
