package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DesignationMst generated by hbm2java
 */
@Entity
@Table(name = "DESIGNATION_MST")
public class DesignationMst implements java.io.Serializable {

	private Long desigId;
	private String designation;
	private String desigAbbr;
	private String activeFlag;
	private Long userId;
	private Date dateTime;
	private Set<LicOblChecklist> licOblChecklists = new HashSet<LicOblChecklist>(
			0);
	private Set<UserMst> userMsts = new HashSet<UserMst>(0);
	private Set<LicOblApplicationMst> licOblApplicationMsts = new HashSet<LicOblApplicationMst>(
			0);

	public DesignationMst() {
	}

	public DesignationMst(Long desigId) {
		this.desigId = desigId;
	}

	public DesignationMst(Long desigId, String designation,
			String desigAbbr, String activeFlag, Long userId,
			Date dateTime, Set<LicOblChecklist> licOblChecklists,
			Set<UserMst> userMsts,
			Set<LicOblApplicationMst> licOblApplicationMsts) {
		this.desigId = desigId;
		this.designation = designation;
		this.desigAbbr = desigAbbr;
		this.activeFlag = activeFlag;
		this.userId = userId;
		this.dateTime = dateTime;
		this.licOblChecklists = licOblChecklists;
		this.userMsts = userMsts;
		this.licOblApplicationMsts = licOblApplicationMsts;
	}

	@Id
	@Column(name = "DESIG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getDesigId() {
		return this.desigId;
	}

	public void setDesigId(Long desigId) {
		this.desigId = desigId;
	}

	@Column(name = "DESIGNATION", length = 30)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "DESIG_ABBR", length = 3)
	public String getDesigAbbr() {
		return this.desigAbbr;
	}

	public void setDesigAbbr(String desigAbbr) {
		this.desigAbbr = desigAbbr;
	}

	@Column(name = "ACTIVE_FLAG", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "designationMst")
	public Set<LicOblChecklist> getLicOblChecklists() {
		return this.licOblChecklists;
	}

	public void setLicOblChecklists(Set<LicOblChecklist> licOblChecklists) {
		this.licOblChecklists = licOblChecklists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "designationMst")
	public Set<UserMst> getUserMsts() {
		return this.userMsts;
	}

	public void setUserMsts(Set<UserMst> userMsts) {
		this.userMsts = userMsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "designationMst")
	public Set<LicOblApplicationMst> getLicOblApplicationMsts() {
		return this.licOblApplicationMsts;
	}

	public void setLicOblApplicationMsts(
			Set<LicOblApplicationMst> licOblApplicationMsts) {
		this.licOblApplicationMsts = licOblApplicationMsts;
	}

}
