package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HoMst generated by hbm2java
 */
@Entity
@Table(name = "HO_MST")
public class HoMst implements java.io.Serializable {

	private Long hoId;
	private StateMst stateMst;
	private String hoName;
	private String hoAbbr;
	private String hoCode;
	private String addr1;
	private String addr2;
	private String addr3;
	private String city;
	private Long pin;
	private String phone;
	private String mobile;
	private String email;
	private String activeFlag;
	private String remarks;
	private Long userId;
	private Date dateTime;
	private Set<UserMst> userMsts = new HashSet<UserMst>(0);

	public HoMst() {
	}

	public HoMst(Long hoId) {
		this.hoId = hoId;
	}

	public HoMst(Long hoId, StateMst stateMst, String hoName,
			String hoAbbr, String hoCode, String addr1, String addr2,
			String addr3, String city, Long pin, String phone,
			String mobile, String email, String activeFlag, String remarks,
			Long userId, Date dateTime, Set<UserMst> userMsts) {
		this.hoId = hoId;
		this.stateMst = stateMst;
		this.hoName = hoName;
		this.hoAbbr = hoAbbr;
		this.hoCode = hoCode;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.addr3 = addr3;
		this.city = city;
		this.pin = pin;
		this.phone = phone;
		this.mobile = mobile;
		this.email = email;
		this.activeFlag = activeFlag;
		this.remarks = remarks;
		this.userId = userId;
		this.dateTime = dateTime;
		this.userMsts = userMsts;
	}

	@Id
	@Column(name = "HO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getHoId() {
		return this.hoId;
	}

	public void setHoId(Long hoId) {
		this.hoId = hoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_ID")
	public StateMst getStateMst() {
		return this.stateMst;
	}

	public void setStateMst(StateMst stateMst) {
		this.stateMst = stateMst;
	}

	@Column(name = "HO_NAME", length = 30)
	public String getHoName() {
		return this.hoName;
	}

	public void setHoName(String hoName) {
		this.hoName = hoName;
	}

	@Column(name = "HO_ABBR", length = 3)
	public String getHoAbbr() {
		return this.hoAbbr;
	}

	public void setHoAbbr(String hoAbbr) {
		this.hoAbbr = hoAbbr;
	}

	@Column(name = "HO_CODE", length = 15)
	public String getHoCode() {
		return this.hoCode;
	}

	public void setHoCode(String hoCode) {
		this.hoCode = hoCode;
	}

	@Column(name = "ADDR_1", length = 250)
	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	@Column(name = "ADDR_2", length = 30)
	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "ADDR_3", length = 30)
	public String getAddr3() {
		return this.addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	@Column(name = "CITY", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "PIN", precision = 22, scale = 0)
	public Long getPin() {
		return this.pin;
	}

	public void setPin(Long pin) {
		this.pin = pin;
	}

	@Column(name = "PHONE", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "MOBILE", length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ACTIVE_FLAG", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "REMARKS", length = 20)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoMst")
	public Set<UserMst> getUserMsts() {
		return this.userMsts;
	}

	public void setUserMsts(Set<UserMst> userMsts) {
		this.userMsts = userMsts;
	}

}
