package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LicAddressDtls generated by hbm2java
 */
@Entity
@Table(name = "LIC_ADDRESS_DTLS")
public class LicAddressDtls implements java.io.Serializable {

	private Long id;
	private StateMst stateMst;
	private String address1;
	private String address2;
	private String address3;
	private String address4;
	private String stateName;
	private String pin;
	private String city;
	private String village;
	private String cityVillageFlag;
	private Long createdBy;
	private Long modifiedBy;
	private Long deletedBy;
	private Date createdDate;
	private Date modifiedDate;
	private Date deletedDate;
	private String deleteFlag;
	private List<LicProposerAddressMapping> licProposerAddressMappings = new ArrayList<LicProposerAddressMapping>();
	private List<LicInsuredAddressMapping> licInsuredAddressMappings = new ArrayList<LicInsuredAddressMapping>();
	private List<LicNomineeAddressMapping> licNomineeAddressMappings = new ArrayList<LicNomineeAddressMapping>();

	public LicAddressDtls() {
	}

	public LicAddressDtls(Long id, StateMst stateMst) {
		this.id = id;
		this.stateMst = stateMst;
	}

	

	@Id
	@SequenceGenerator(name="LIC_ADD_DTLS_SEQ",sequenceName="LIC_ADD_DTLS_SEQ")
	@GeneratedValue(generator="LIC_ADD_DTLS_SEQ",strategy=GenerationType.AUTO)
	@Column(name = "ID", nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_MST_ID", nullable = false)
	public StateMst getStateMst() {
		return this.stateMst;
	}

	public void setStateMst(StateMst stateMst) {
		this.stateMst = stateMst;
	}

	@Column(name = "ADDRESS1", length = 500)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "ADDRESS2", length = 500)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "ADDRESS3", length = 500)
	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	@Column(name = "ADDRESS4", length = 500)
	public String getAddress4() {
		return this.address4;
	}

	public void setAddress4(String address4) {
		this.address4 = address4;
	}

	@Column(name = "STATE_NAME", length = 50)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@Column(name = "PIN", length=7)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "CITY", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "VILLAGE", length = 100)
	public String getVillage() {
		return this.village;
	}

	public void setVillage(String village) {
		this.village = village;
	}

	@Column(name = "CITY_VILLAGE_FLAG", length = 1)
	public String getCityVillageFlag() {
		return this.cityVillageFlag;
	}

	public void setCityVillageFlag(String cityVillageFlag) {
		this.cityVillageFlag = cityVillageFlag;
	}

	@Column(name = "CREATED_BY", precision = 22, scale = 0)
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "MODIFIED_BY", precision = 22, scale = 0)
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "DELETED_BY", precision = 22, scale = 0)
	public Long getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(Long deletedBy) {
		this.deletedBy = deletedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELETED_DATE", length = 7)
	public Date getDeletedDate() {
		return this.deletedDate;
	}

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	@Column(name = "DELETE_FLAG", length = 1)
	public String getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licAddressDtls")
	public List<LicProposerAddressMapping> getLicProposerAddressMappings() {
		return this.licProposerAddressMappings;
	}

	public void setLicProposerAddressMappings(
			List<LicProposerAddressMapping> licProposerAddressMappings) {
		this.licProposerAddressMappings = licProposerAddressMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licAddressDtls")
	public List<LicInsuredAddressMapping> getLicInsuredAddressMappings() {
		return this.licInsuredAddressMappings;
	}

	public void setLicInsuredAddressMappings(
			List<LicInsuredAddressMapping> licInsuredAddressMappings) {
		this.licInsuredAddressMappings = licInsuredAddressMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licAddressDtls")
	public List<LicNomineeAddressMapping> getLicNomineeAddressMappings() {
		return this.licNomineeAddressMappings;
	}

	public void setLicNomineeAddressMappings(
			List<LicNomineeAddressMapping> licNomineeAddressMappings) {
		this.licNomineeAddressMappings = licNomineeAddressMappings;
	}

}
