package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * LicHubMst generated by hbm2java
 */
@Entity
@Table(name = "LIC_HUB_MST", uniqueConstraints = @UniqueConstraint(columnNames = "HUB_NAME"))
public class LicHubMst implements java.io.Serializable {

	private Long id;
	private String hubName;
	private Long createdBy;
	private Long modifiedBy;
	private Long deletedBy;
	private Date createdDate;
	private Date modifiedDate;
	private Date deletedDate;
	private String deleteFlag;
	
	private List<LicBranchHubMap> licBranchHubMaps = new ArrayList<LicBranchHubMap>(0);
	private List<LicOblApplicationMst> licOblApplicationMsts = new ArrayList<LicOblApplicationMst>(0);
	private List<LicPolicyDtls> licPolicyDtlses = new ArrayList<LicPolicyDtls>();
	private List<LicPolicyMst> licPolicyMsts = new ArrayList<LicPolicyMst>();
	private List<LicRequirementDtls> licRequirementDtlses = new ArrayList<LicRequirementDtls>();
	private List<LicPolicyDtls> licPolicyDtlsesforProcessHubMst = new ArrayList<LicPolicyDtls>();

	public LicHubMst() {
	}

	public LicHubMst(Long id, String hubName) {
		this.id = id;
		this.hubName = hubName;
	}

	public LicHubMst(Long id, String hubName, Long createdBy,
			Long modifiedBy, Long deletedBy, Date createdDate,
			Date modifiedDate, Date deletedDate, String deleteFlag) {
		this.id = id;
		this.hubName = hubName;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.deletedBy = deletedBy;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.deletedDate = deletedDate;
		this.deleteFlag = deleteFlag;
	}

	@Id
	@Column(name = "ID", nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@Column(name = "HUB_NAME", nullable = false, length = 50)
	public String getHubName() {
		return this.hubName;
	}

	public void setHubName(String hubName) {
		this.hubName = hubName;
	}

	
	@Column(name = "CREATED_BY", precision = 22, scale = 0)
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	
	@Column(name = "MODIFIED_BY", precision = 22, scale = 0)
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	
	@Column(name = "DELETED_BY", precision = 22, scale = 0)
	public Long getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(Long deletedBy) {
		this.deletedBy = deletedBy;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "DELETED_DATE", length = 7)
	public Date getDeletedDate() {
		return this.deletedDate;
	}

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	
	@Column(name = "DELETE_FLAG", length = 1)
	public String getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licHubMst")
	public List<LicBranchHubMap> getLicBranchHubMaps() {
		return licBranchHubMaps;
	}

	public void setLicBranchHubMaps(List<LicBranchHubMap> licBranchHubMaps) {
		this.licBranchHubMaps = licBranchHubMaps;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oblHubMst")
	public List<LicOblApplicationMst> getLicOblApplicationMsts() {
		return licOblApplicationMsts;
	}

	public void setLicOblApplicationMsts(
			List<LicOblApplicationMst> licOblApplicationMsts) {
		this.licOblApplicationMsts = licOblApplicationMsts;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oblHubMst")
	public List<LicPolicyDtls> getLicPolicyDtlses() {
		return licPolicyDtlses;
	}

	public void setLicPolicyDtlses(List<LicPolicyDtls> licPolicyDtlses) {
		this.licPolicyDtlses = licPolicyDtlses;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sentHub")
	public List<LicPolicyMst> getLicPolicyMsts() {
		return licPolicyMsts;
	}

	public void setLicPolicyMsts(List<LicPolicyMst> licPolicyMsts) {
		this.licPolicyMsts = licPolicyMsts;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licHubMst")
	public List<LicRequirementDtls> getLicRequirementDtlses() {
		return licRequirementDtlses;
	}

	public void setLicRequirementDtlses(
			List<LicRequirementDtls> licRequirementDtlses) {
		this.licRequirementDtlses = licRequirementDtlses;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processHubMst")
	public List<LicPolicyDtls> getLicPolicyDtlsesforProcessHubMst() {
		return licPolicyDtlsesforProcessHubMst;
	}

	public void setLicPolicyDtlsesforProcessHubMst(
			List<LicPolicyDtls> licPolicyDtlsesforProcessHubMst) {
		this.licPolicyDtlsesforProcessHubMst = licPolicyDtlsesforProcessHubMst;
	}
}
