package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LicNomineeDtls generated by hbm2java
 */
@Entity
@Table(name = "LIC_NOMINEE_DTLS")
public class LicNomineeDtls implements java.io.Serializable {

	private Long id;
	private LicOblApplicationMst licOblApplicationMst;
	private String nomineeName;
	private String nomineeRlnshp;
	private Date nomineeDob;
	private Long nomineeAddrId;
	private String appointeeName;
	private String appointeeRlnshp;
	private Date appointeeDob;
	private String appointeeGender;
	private String appointeeEduQual;
	private String nomineeAddress;
	private Long nomineeAge;
	private Long createdBy;
	private Long modifiedBy;
	private Long deletedBy;
	private Date createdDate;
	private Date modifiedDate;
	private Date deletedDate;
	private String deleteFlag;
	private Set<LicNomineeAddressMapping> licNomineeAddressMappings = new HashSet<LicNomineeAddressMapping>(0);

	public LicNomineeDtls() {
	}

	public LicNomineeDtls(Long id, Long nomineeAddrId) {
		this.id = id;
		this.nomineeAddrId = nomineeAddrId;
	}

	public LicNomineeDtls(Long id,
			LicOblApplicationMst licOblApplicationMst, String nomineeName,
			String nomineeRlnshp, Date nomineeDob, Long nomineeAddrId,
			String appointeeName, String appointeeRlnshp, Date appointeeDob,
			String appointeeGender, String appointeeEduQual,
			Long createdBy, Long modifiedBy, Long deletedBy,
			Date createdDate, Date modifiedDate, Date deletedDate,
			String deleteFlag,
			Set<LicNomineeAddressMapping> licNomineeAddressMappings) {
		this.id = id;
		this.licOblApplicationMst = licOblApplicationMst;
		this.nomineeName = nomineeName;
		this.nomineeRlnshp = nomineeRlnshp;
		this.nomineeDob = nomineeDob;
		this.nomineeAddrId = nomineeAddrId;
		this.appointeeName = appointeeName;
		this.appointeeRlnshp = appointeeRlnshp;
		this.appointeeDob = appointeeDob;
		this.appointeeGender = appointeeGender;
		this.appointeeEduQual = appointeeEduQual;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.deletedBy = deletedBy;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.deletedDate = deletedDate;
		this.deleteFlag = deleteFlag;
		this.licNomineeAddressMappings = licNomineeAddressMappings;
	}

	
	@Id
	@SequenceGenerator(name="LIC_NOMINEE_DTLS_SEQ",sequenceName="LIC_NOMINEE_DTLS_SEQ")
	@GeneratedValue(generator="LIC_NOMINEE_DTLS_SEQ",strategy=GenerationType.AUTO)
	@Column(name = "ID", nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LIC_OBL_APPL_MST_ID")
	public LicOblApplicationMst getLicOblApplicationMst() {
		return this.licOblApplicationMst;
	}

	public void setLicOblApplicationMst(
			LicOblApplicationMst licOblApplicationMst) {
		this.licOblApplicationMst = licOblApplicationMst;
	}

	
	@Column(name = "NOMINEE_NAME", length = 50)
	public String getNomineeName() {
		return this.nomineeName;
	}

	public void setNomineeName(String nomineeName) {
		this.nomineeName = nomineeName;
	}
	
	
	@Column(name = "NOMINEE_ADDRESS", length = 500)
	public String getNomineeAddress() {
		return nomineeAddress;
	}

	public void setNomineeAddress(String nomineeAddress) {
		this.nomineeAddress = nomineeAddress;
	}

	
	@Column(name = "NOMINEE_RLNSHP", length = 50)
	public String getNomineeRlnshp() {
		return this.nomineeRlnshp;
	}

	public void setNomineeRlnshp(String nomineeRlnshp) {
		this.nomineeRlnshp = nomineeRlnshp;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "NOMINEE_DOB", length = 7)
	public Date getNomineeDob() {
		return this.nomineeDob;
	}

	public void setNomineeDob(Date nomineeDob) {
		this.nomineeDob = nomineeDob;
	}

	
	@Column(name = "NOMINEE_ADDR_ID", precision = 22, scale = 0)
	public Long getNomineeAddrId() {
		return this.nomineeAddrId;
	}

	public void setNomineeAddrId(Long nomineeAddrId) {
		this.nomineeAddrId = nomineeAddrId;
	}

	
	@Column(name = "APPOINTEE_NAME", length = 50)
	public String getAppointeeName() {
		return this.appointeeName;
	}

	public void setAppointeeName(String appointeeName) {
		this.appointeeName = appointeeName;
	}

	
	@Column(name = "APPOINTEE_RLNSHP", length = 50)
	public String getAppointeeRlnshp() {
		return this.appointeeRlnshp;
	}

	public void setAppointeeRlnshp(String appointeeRlnshp) {
		this.appointeeRlnshp = appointeeRlnshp;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "APPOINTEE_DOB", length = 7)
	public Date getAppointeeDob() {
		return this.appointeeDob;
	}

	public void setAppointeeDob(Date appointeeDob) {
		this.appointeeDob = appointeeDob;
	}

	
	@Column(name = "APPOINTEE_GENDER", length = 1)
	public String getAppointeeGender() {
		return this.appointeeGender;
	}

	public void setAppointeeGender(String appointeeGender) {
		this.appointeeGender = appointeeGender;
	}

	
	@Column(name = "APPOINTEE_EDU_QUAL", length = 50)
	public String getAppointeeEduQual() {
		return this.appointeeEduQual;
	}

	public void setAppointeeEduQual(String appointeeEduQual) {
		this.appointeeEduQual = appointeeEduQual;
	}

	@Column(name = "NOMINEE_AGE", precision = 22, scale = 0)
	public Long getNomineeAge() {
		return nomineeAge;
	}

	public void setNomineeAge(Long nomineeAge) {
		this.nomineeAge = nomineeAge;
	}

	@Column(name = "CREATED_BY", precision = 22, scale = 0)
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	
	@Column(name = "MODIFIED_BY", precision = 22, scale = 0)
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	
	@Column(name = "DELETED_BY", precision = 22, scale = 0)
	public Long getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(Long deletedBy) {
		this.deletedBy = deletedBy;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "DELETED_DATE", length = 7)
	public Date getDeletedDate() {
		return this.deletedDate;
	}

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	
	@Column(name = "DELETE_FLAG", length = 1)
	public String getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licNomineeDtls")
	public Set<LicNomineeAddressMapping> getLicNomineeAddressMappings() {
		return this.licNomineeAddressMappings;
	}

	public void setLicNomineeAddressMappings(
			Set<LicNomineeAddressMapping> licNomineeAddressMappings) {
		this.licNomineeAddressMappings = licNomineeAddressMappings;
	}

}
