package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * LicProposerDtls generated by hbm2java
 */
@Entity
@Table(name = "LIC_PROPOSER_DTLS")
public class LicProposerDtls implements java.io.Serializable {

	private Long id;
	private String salutation;
	private String name;
	private Date dob;
	private String gender;
	private String guardianName;
	private String guardianType;
	private Long phoneNo;
	private Long mobileNo;
	private String email;
	private Long height;
	private Long weight;
	private String pan;
	private String addrProof;
	private String incomeProof;
	private String nationality;
	private String maritalStatus;
	private String eduQual;
	private String ageProofNature;
	private String identityProof;
	private String occupation;
	private Long annualIncome;
	private Long createdBy;
	private Long modifiedBy;
	private Long deletedBy;
	private Date createdDate;
	private Date modifiedDate;
	private Date deletedDate;
	private String deleteFlag;
	private Set<LicProposerAddressMapping> licProposerAddressMappings = new HashSet<LicProposerAddressMapping>(0);
	private LicOblApplicationMst licOblApplicationMst;

	public LicProposerDtls() {
	}

	public LicProposerDtls(Long id) {
		this.id = id;
	}

	
	@Id
	@GenericGenerator(name = "proposerGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "licOblApplicationMst"))
	@GeneratedValue(generator="proposerGenerator")
	@Column(name = "ID", nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@Column(name = "SALUTATION", length = 50)
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	
	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 7)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	
	@Column(name = "GENDER", length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	
	@Column(name = "GUARDIAN_NAME", length = 50)
	public String getGuardianName() {
		return this.guardianName;
	}

	public void setGuardianName(String guardianName) {
		this.guardianName = guardianName;
	}

	
	@Column(name = "GUARDIAN_TYPE", length = 50)
	public String getGuardianType() {
		return this.guardianType;
	}

	public void setGuardianType(String guardianType) {
		this.guardianType = guardianType;
	}

	
	@Column(name = "PHONE_NO", precision = 22, scale = 0)
	public Long getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(Long phoneNo) {
		this.phoneNo = phoneNo;
	}

	
	@Column(name = "MOBILE_NO", precision = 22, scale = 0)
	public Long getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(Long mobileNo) {
		this.mobileNo = mobileNo;
	}

	
	@Column(name = "EMAIL", length = 150)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	
	@Column(name = "HEIGHT", precision = 22, scale = 0)
	public Long getHeight() {
		return this.height;
	}

	public void setHeight(Long height) {
		this.height = height;
	}

	
	@Column(name = "WEIGHT", precision = 22, scale = 0)
	public Long getWeight() {
		return this.weight;
	}

	public void setWeight(Long weight) {
		this.weight = weight;
	}

	
	@Column(name = "PAN", length = 50)
	public String getPan() {
		return this.pan;
	}

	public void setPan(String pan) {
		this.pan = pan;
	}

	
	@Column(name = "ADDR_PROOF", length = 500)
	public String getAddrProof() {
		return this.addrProof;
	}

	public void setAddrProof(String addrProof) {
		this.addrProof = addrProof;
	}

	
	@Column(name = "INCOME_PROOF", length = 500)
	public String getIncomeProof() {
		return this.incomeProof;
	}

	public void setIncomeProof(String incomeProof) {
		this.incomeProof = incomeProof;
	}

	
	@Column(name = "NATIONALITY", length = 50)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	
	@Column(name = "MARITAL_STATUS", length = 10)
	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	
	@Column(name = "EDU_QUAL", length = 50)
	public String getEduQual() {
		return this.eduQual;
	}

	public void setEduQual(String eduQual) {
		this.eduQual = eduQual;
	}

	
	@Column(name = "AGE_PROOF_NATURE", length = 500)
	public String getAgeProofNature() {
		return this.ageProofNature;
	}

	public void setAgeProofNature(String ageProofNature) {
		this.ageProofNature = ageProofNature;
	}

	
	@Column(name = "IDENTITY_PROOF", length = 500)
	public String getIdentityProof() {
		return this.identityProof;
	}

	public void setIdentityProof(String identityProof) {
		this.identityProof = identityProof;
	}

	
	@Column(name = "OCCUPATION", length = 50)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	
	@Column(name = "ANNUAL_INCOME", precision = 22, scale = 0)
	public Long getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(Long annualIncome) {
		this.annualIncome = annualIncome;
	}

	
	@Column(name = "CREATED_BY", precision = 22, scale = 0)
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	
	@Column(name = "MODIFIED_BY", precision = 22, scale = 0)
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	
	@Column(name = "DELETED_BY", precision = 22, scale = 0)
	public Long getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(Long deletedBy) {
		this.deletedBy = deletedBy;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "DELETED_DATE", length = 7)
	public Date getDeletedDate() {
		return this.deletedDate;
	}

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	
	@Column(name = "DELETE_FLAG", length = 1)
	public String getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licProposerDtls")
	public Set<LicProposerAddressMapping> getLicProposerAddressMappings() {
		return this.licProposerAddressMappings;
	}

	public void setLicProposerAddressMappings(
			Set<LicProposerAddressMapping> licProposerAddressMappings) {
		this.licProposerAddressMappings = licProposerAddressMappings;
	}

	
	@OneToOne(fetch=FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public LicOblApplicationMst getLicOblApplicationMst() {
		return licOblApplicationMst;
	}

	public void setLicOblApplicationMst(LicOblApplicationMst licOblApplicationMst) {
		this.licOblApplicationMst = licOblApplicationMst;
	}
}
