package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LicProductMst generated by hbm2java
 */

@Entity
@Table(name = "LIC_PRODUCT_MST")
public class LicProductMst implements java.io.Serializable {

	private Long id;
	private String prodDesc;
	private Long renwlPeriod;
	private Long extRenwlPeriod;
	private Long lapsedDuration;
	private String hlthDeclReqd;
	private Long hlthDeclValidity;
	private Long hlthDeclDuration;
	private Long roundMnths;
	private Long roundDays;
	private Double serviceTax;
	private String prodType;
	private String backdatingFlag;
	private Long createdBy;
	private Long modifiedBy;
	private Long deletedBy;
	private Date createdDate;
	private Date modifiedDate;
	private Date deletedDate;
	private String deleteFlag;
	private Set<LicProductValueMst> licProductValueMsts = new HashSet<LicProductValueMst>(0);	
	private Set<LicBusinessTxn> licBusinessTxns = new HashSet<LicBusinessTxn>(0);	
	private List<LicTabPremMst> licTabPremMsts = new ArrayList<LicTabPremMst>();
	private List<LicModeRebateMst> licModeRebateMsts = new ArrayList<LicModeRebateMst>();
	private List<LicPremFreqAllowARMst> licPremFreqAllowARMsts = new ArrayList<LicPremFreqAllowARMst>();
	private List<LicHighSaDiscMst> licHighSaDiscMsts = new ArrayList<LicHighSaDiscMst>();
	private List<LicNsapMst> licNsapMsts = new ArrayList<LicNsapMst>();
	private List<LicCollBenPctMst> licCollBenPctMsts = new ArrayList<LicCollBenPctMst>();
	private List<LicNsapDocMst> licNsapDocMsts = new ArrayList<LicNsapDocMst>();
	private List<LicProdFineMst> licProdFineMsts = new ArrayList<LicProdFineMst>();
	
	public LicProductMst() {
	}

	
	@Id
	@Column(name = "ID", nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}
	public void setId(Long id) {
		this.id = id;
	}

	
	@Column(name = "PROD_DESC", length = 75)
	public String getProdDesc() {
		return this.prodDesc;
	}
	public void setProdDesc(String prodDesc) {
		this.prodDesc = prodDesc;
	}
	

	@Column(name = "RENWL_PERIOD", precision = 22, scale = 0)
	public Long getRenwlPeriod() {
		return this.renwlPeriod;
	}
	public void setRenwlPeriod(Long renwlPeriod) {
		this.renwlPeriod = renwlPeriod;
	}

	
	@Column(name = "EXT_RENWL_PERIOD", precision = 22, scale = 0)
	public Long getExtRenwlPeriod() {
		return this.extRenwlPeriod;
	}
	public void setExtRenwlPeriod(Long extRenwlPeriod) {
		this.extRenwlPeriod = extRenwlPeriod;
	}

	
	@Column(name = "LAPSED_DURATION", precision = 22, scale = 0)
	public Long getLapsedDuration() {
		return this.lapsedDuration;
	}
	public void setLapsedDuration(Long lapsedDuration) {
		this.lapsedDuration = lapsedDuration;
	}

	
	@Column(name = "HLTH_DECL_REQD", length = 1)
	public String getHlthDeclReqd() {
		return this.hlthDeclReqd;
	}
	public void setHlthDeclReqd(String hlthDeclReqd) {
		this.hlthDeclReqd = hlthDeclReqd;
	}

	
	@Column(name = "HLTH_DECL_VALIDITY", precision = 22, scale = 0)
	public Long getHlthDeclValidity() {
		return this.hlthDeclValidity;
	}
	public void setHlthDeclValidity(Long hlthDeclValidity) {
		this.hlthDeclValidity = hlthDeclValidity;
	}

	@Column(name = "HLTH_DECL_DURATION", precision = 22, scale = 0)
	public Long getHlthDeclDuration() {
		return this.hlthDeclDuration;
	}
	public void setHlthDeclDuration(Long hlthDeclDuration) {
		this.hlthDeclDuration = hlthDeclDuration;
	}

	
	@Column(name = "ROUND_MNTHS", precision = 22, scale = 0)
	public Long getRoundMnths() {
		return this.roundMnths;
	}
	public void setRoundMnths(Long roundMnths) {
		this.roundMnths = roundMnths;
	}

	
	@Column(name = "ROUND_DAYS", precision = 22, scale = 0)
	public Long getRoundDays() {
		return this.roundDays;
	}
	public void setRoundDays(Long roundDays) {
		this.roundDays = roundDays;
	}

	
	@Column(name = "PROD_TYPE", length = 1)
	public String getProdType() {
		return this.prodType;
	}
	public void setProdType(String prodType) {
		this.prodType = prodType;
	}

	
	@Column(name = "CREATED_BY", precision = 22, scale = 0)
	public Long getCreatedBy() {
		return this.createdBy;
	}
	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	
	@Column(name = "MODIFIED_BY", precision = 22, scale = 0)
	public Long getModifiedBy() {
		return this.modifiedBy;
	}
	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	
	@Column(name = "DELETED_BY", precision = 22, scale = 0)
	public Long getDeletedBy() {
		return this.deletedBy;
	}
	public void setDeletedBy(Long deletedBy) {
		this.deletedBy = deletedBy;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", length = 7)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "DELETED_DATE", length = 7)
	public Date getDeletedDate() {
		return this.deletedDate;
	}
	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	
	@Column(name = "DELETE_FLAG", length = 1)
	public String getDeleteFlag() {
		return this.deleteFlag;
	}
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licProductMst")
	public Set<LicProductValueMst> getLicProductValueMsts() {
		return this.licProductValueMsts;
	}
	public void setLicProductValueMsts(Set<LicProductValueMst> licProductValueMsts) {
		this.licProductValueMsts = licProductValueMsts;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licProductMst")
	public Set<LicBusinessTxn> getLicBusinessTxns() {
		return licBusinessTxns;
	}
	public void setLicBusinessTxns(Set<LicBusinessTxn> licBusinessTxns) {
		this.licBusinessTxns = licBusinessTxns;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licProductMst")
	public List<LicTabPremMst> getLicTabPremMsts() {
		return licTabPremMsts;
	}
	public void setLicTabPremMsts(List<LicTabPremMst> licTabPremMsts) {
		this.licTabPremMsts = licTabPremMsts;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licProductMst")
	public List<LicNsapMst> getLicNsapMsts() {
		return licNsapMsts;
	}
	public void setLicNsapMsts(List<LicNsapMst> licNsapMsts) {
		this.licNsapMsts = licNsapMsts;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licProductMst")
	public List<LicModeRebateMst> getLicModeRebateMsts() {
		return licModeRebateMsts;
	}
	public void setLicModeRebateMsts(List<LicModeRebateMst> licModeRebateMsts) {
		this.licModeRebateMsts = licModeRebateMsts;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licProductMst")
	public List<LicPremFreqAllowARMst> getLicPremFreqAllowARMsts() {
		return licPremFreqAllowARMsts;
	}
	public void setLicPremFreqAllowARMsts(
			List<LicPremFreqAllowARMst> licPremFreqAllowARMsts) {
		this.licPremFreqAllowARMsts = licPremFreqAllowARMsts;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licProductMst")
	public List<LicHighSaDiscMst> getLicHighSaDiscMsts() {
		return licHighSaDiscMsts;
	}
	public void setLicHighSaDiscMsts(List<LicHighSaDiscMst> licHighSaDiscMsts) {
		this.licHighSaDiscMsts = licHighSaDiscMsts;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licProductMst")
	public List<LicCollBenPctMst> getLicCollBenPctMsts() {
		return licCollBenPctMsts;
	}	
	public void setLicCollBenPctMsts(List<LicCollBenPctMst> licCollBenPctMsts) {
		this.licCollBenPctMsts = licCollBenPctMsts;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licProductMst")
	public List<LicNsapDocMst> getLicNsapDocMsts() {
		return licNsapDocMsts;
	}
	public void setLicNsapDocMsts(List<LicNsapDocMst> licNsapDocMsts) {
		this.licNsapDocMsts = licNsapDocMsts;
	}
	
	
	@Column(name = "SERVICE_TAX", precision = 22, scale = 0)
	public Double getServiceTax() {
		return serviceTax;
	}
	public void setServiceTax(Double serviceTax) {
		this.serviceTax = serviceTax;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licProductMst")
	public List<LicProdFineMst> getLicProdFineMsts() {
		return licProdFineMsts;
	}
	public void setLicProdFineMsts(List<LicProdFineMst> licProdFineMsts) {
		this.licProdFineMsts = licProdFineMsts;
	}

	@Column(name="BACKDATION_FLAG",length=1)
	public String getBackdatingFlag() {
		return backdatingFlag;
	}
	public void setBackdatingFlag(String backdatingFlag) {
		this.backdatingFlag = backdatingFlag;
	}
}
