package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParentCompyMst generated by hbm2java
 */
@Entity
@Table(name = "PARENT_COMPY_MST")
public class ParentCompyMst implements java.io.Serializable {

	private Long prntCompyId;
	private String prntCompyName;
	private String prntCompyAbbr;
	private String addr1;
	private String addr2;
	private String addr3;
	private Long pin;
	private String city;
	private Long stateId;
	private String compyPhone;
	private String compyEmail;
	private String personName;
	private String personMobile;
	private String personPhone;
	private String personEmail;
	private String licenseNo;
	private Long userId;
	private Date dateTime;
	private String activeFlag;
	private Set<LicOblApplicationMst> licOblApplicationMsts = new HashSet<LicOblApplicationMst>(0);
	
	private List<PrintRcptMst> printRcptMsts = new ArrayList<PrintRcptMst>();

	public ParentCompyMst() {
	}

	public ParentCompyMst(Long prntCompyId) {
		this.prntCompyId = prntCompyId;
	}

	
	@Id
	@Column(name = "PRNT_COMPY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getPrntCompyId() {
		return this.prntCompyId;
	}

	public void setPrntCompyId(Long prntCompyId) {
		this.prntCompyId = prntCompyId;
	}

	
	@Column(name = "PRNT_COMPY_NAME", length = 50)
	public String getPrntCompyName() {
		return this.prntCompyName;
	}

	public void setPrntCompyName(String prntCompyName) {
		this.prntCompyName = prntCompyName;
	}

	
	@Column(name = "PRNT_COMPY_ABBR", length = 5)
	public String getPrntCompyAbbr() {
		return this.prntCompyAbbr;
	}

	public void setPrntCompyAbbr(String prntCompyAbbr) {
		this.prntCompyAbbr = prntCompyAbbr;
	}

	
	@Column(name = "ADDR1", length = 50)
	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	
	@Column(name = "ADDR2", length = 50)
	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	
	@Column(name = "ADDR3", length = 50)
	public String getAddr3() {
		return this.addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	
	@Column(name = "PIN", precision = 22, scale = 0)
	public Long getPin() {
		return this.pin;
	}

	public void setPin(Long pin) {
		this.pin = pin;
	}

	
	@Column(name = "CITY", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	
	@Column(name = "STATE_ID", precision = 22, scale = 0)
	public Long getStateId() {
		return this.stateId;
	}

	public void setStateId(Long stateId) {
		this.stateId = stateId;
	}

	
	@Column(name = "COMPY_PHONE", length = 50)
	public String getCompyPhone() {
		return this.compyPhone;
	}

	public void setCompyPhone(String compyPhone) {
		this.compyPhone = compyPhone;
	}

	
	@Column(name = "COMPY_EMAIL", length = 50)
	public String getCompyEmail() {
		return this.compyEmail;
	}

	public void setCompyEmail(String compyEmail) {
		this.compyEmail = compyEmail;
	}

	
	@Column(name = "PERSON_NAME", length = 50)
	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	
	@Column(name = "PERSON_MOBILE", length = 15)
	public String getPersonMobile() {
		return this.personMobile;
	}

	public void setPersonMobile(String personMobile) {
		this.personMobile = personMobile;
	}

	
	@Column(name = "PERSON_PHONE", length = 50)
	public String getPersonPhone() {
		return this.personPhone;
	}

	public void setPersonPhone(String personPhone) {
		this.personPhone = personPhone;
	}

	
	@Column(name = "PERSON_EMAIL", length = 50)
	public String getPersonEmail() {
		return this.personEmail;
	}

	public void setPersonEmail(String personEmail) {
		this.personEmail = personEmail;
	}

	
	@Column(name = "LICENSE_NO", length = 15)
	public String getLicenseNo() {
		return this.licenseNo;
	}

	public void setLicenseNo(String licenseNo) {
		this.licenseNo = licenseNo;
	}

	
	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	
	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	
	@Column(name = "ACTIVE_FLAG", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentCompyMst")
	public Set<LicOblApplicationMst> getLicOblApplicationMsts() {
		return this.licOblApplicationMsts;
	}

	public void setLicOblApplicationMsts(
			Set<LicOblApplicationMst> licOblApplicationMsts) {
		this.licOblApplicationMsts = licOblApplicationMsts;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentCompyMst")
	public List<PrintRcptMst> getPrintRcptMsts() {
		return printRcptMsts;
	}

	public void setPrintRcptMsts(List<PrintRcptMst> printRcptMsts) {
		this.printRcptMsts = printRcptMsts;
	}
	
	@Override
	public boolean equals(Object obj) {
		return this.getPrntCompyId().equals(((ParentCompyMst) obj).getPrntCompyId());
	}

}
