package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhaseMst generated by hbm2java
 */
@Entity
@Table(name = "PHASE_MST")
public class PhaseMst implements java.io.Serializable {

	private Long phaseId;
	private String phaseName;
	private Date phFromDate;
	private Date phToDate;
	private String openStatus;
	private String activeFlag;
	private String remarks;
	private Long userId;
	private Date dateTime;
	private String chainFlag;
	private Set<PhaseBaMst> phaseBaMsts = new HashSet<PhaseBaMst>(0);
	private Set<LicOblChecklist> licOblChecklists = new HashSet<LicOblChecklist>(0);
	private Set<AgentRlns> agentRlnses = new HashSet<AgentRlns>(0);	
	private Set<LicBusinessTxn> licBusinessTxns = new HashSet<LicBusinessTxn>(0);
	private List<GenericBusinessTxn> genericBusinessTxns = new ArrayList<GenericBusinessTxn>();

	public PhaseMst() {
	}

	public PhaseMst(Long phaseId) {
		this.phaseId = phaseId;
	}

	public PhaseMst(Long phaseId, String phaseName, Date phFromDate,
			Date phToDate, String openStatus, String activeFlag,
			String remarks, Long userId, Date dateTime,
			String chainFlag, Set<PhaseBaMst> phaseBaMsts,
			Set<LicOblChecklist> licOblChecklists, Set<AgentRlns> agentRlnses) {
		this.phaseId = phaseId;
		this.phaseName = phaseName;
		this.phFromDate = phFromDate;
		this.phToDate = phToDate;
		this.openStatus = openStatus;
		this.activeFlag = activeFlag;
		this.remarks = remarks;
		this.userId = userId;
		this.dateTime = dateTime;
		this.chainFlag = chainFlag;
		this.phaseBaMsts = phaseBaMsts;
		this.licOblChecklists = licOblChecklists;
		this.agentRlnses = agentRlnses;
	}

	@Id
	@Column(name = "PHASE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getPhaseId() {
		return this.phaseId;
	}

	public void setPhaseId(Long phaseId) {
		this.phaseId = phaseId;
	}

	@Column(name = "PHASE_NAME", length = 20)
	public String getPhaseName() {
		return this.phaseName;
	}

	public void setPhaseName(String phaseName) {
		this.phaseName = phaseName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PH_FROM_DATE", length = 7)
	public Date getPhFromDate() {
		return this.phFromDate;
	}

	public void setPhFromDate(Date phFromDate) {
		this.phFromDate = phFromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PH_TO_DATE", length = 7)
	public Date getPhToDate() {
		return this.phToDate;
	}

	public void setPhToDate(Date phToDate) {
		this.phToDate = phToDate;
	}

	@Column(name = "OPEN_STATUS", length = 1)
	public String getOpenStatus() {
		return this.openStatus;
	}

	public void setOpenStatus(String openStatus) {
		this.openStatus = openStatus;
	}

	@Column(name = "ACTIVE_FLAG", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "REMARKS", length = 50)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "CHAIN_FLAG", length = 1)
	public String getChainFlag() {
		return this.chainFlag;
	}

	public void setChainFlag(String chainFlag) {
		this.chainFlag = chainFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phaseMst")
	public Set<PhaseBaMst> getPhaseBaMsts() {
		return this.phaseBaMsts;
	}

	public void setPhaseBaMsts(Set<PhaseBaMst> phaseBaMsts) {
		this.phaseBaMsts = phaseBaMsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phaseMst")
	public Set<LicOblChecklist> getLicOblChecklists() {
		return this.licOblChecklists;
	}

	public void setLicOblChecklists(Set<LicOblChecklist> licOblChecklists) {
		this.licOblChecklists = licOblChecklists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phaseMst")
	public Set<AgentRlns> getAgentRlnses() {
		return this.agentRlnses;
	}

	public void setAgentRlnses(Set<AgentRlns> agentRlnses) {
		this.agentRlnses = agentRlnses;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phaseMst")
	public Set<LicBusinessTxn> getLicBusinessTxns() {
		return licBusinessTxns;
	}

	public void setLicBusinessTxns(Set<LicBusinessTxn> licBusinessTxns) {
		this.licBusinessTxns = licBusinessTxns;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phaseMst")
	public List<GenericBusinessTxn> getGenericBusinessTxns() {
		return genericBusinessTxns;
	}

	public void setGenericBusinessTxns(List<GenericBusinessTxn> genericBusinessTxns) {
		this.genericBusinessTxns = genericBusinessTxns;
	}

}
