package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhaseBaMst generated by hbm2java
 */
@Entity
@Table(name = "PHASE_BA_MST")
public class PhaseBaMst implements java.io.Serializable {

	private Long id;
	private PhaseMst phaseMst;
	private String phaseName;
	private Date baFromDt;
	private Date baToDt;
	private String activeFlag;
	private String openStatus;
	private String remarks;
	private Long userId;
	private Date dateTime;

	public PhaseBaMst() {
	}

	public PhaseBaMst(Long id, PhaseMst phaseMst) {
		this.id = id;
		this.phaseMst = phaseMst;
	}

	public PhaseBaMst(Long id, PhaseMst phaseMst, String phaseName,
			Date baFromDt, Date baToDt, String activeFlag, String openStatus,
			String remarks, Long userId, Date dateTime) {
		this.id = id;
		this.phaseMst = phaseMst;
		this.phaseName = phaseName;
		this.baFromDt = baFromDt;
		this.baToDt = baToDt;
		this.activeFlag = activeFlag;
		this.openStatus = openStatus;
		this.remarks = remarks;
		this.userId = userId;
		this.dateTime = dateTime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHASE_BA_ID", nullable = false)
	public PhaseMst getPhaseMst() {
		return this.phaseMst;
	}

	public void setPhaseMst(PhaseMst phaseMst) {
		this.phaseMst = phaseMst;
	}

	@Column(name = "PHASE_NAME", length = 20)
	public String getPhaseName() {
		return this.phaseName;
	}

	public void setPhaseName(String phaseName) {
		this.phaseName = phaseName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BA_FROM_DT", length = 7)
	public Date getBaFromDt() {
		return this.baFromDt;
	}

	public void setBaFromDt(Date baFromDt) {
		this.baFromDt = baFromDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BA_TO_DT", length = 7)
	public Date getBaToDt() {
		return this.baToDt;
	}

	public void setBaToDt(Date baToDt) {
		this.baToDt = baToDt;
	}

	@Column(name = "ACTIVE_FLAG", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "OPEN_STATUS", length = 1)
	public String getOpenStatus() {
		return this.openStatus;
	}

	public void setOpenStatus(String openStatus) {
		this.openStatus = openStatus;
	}

	@Column(name = "REMARKS", length = 20)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
