package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PicBranchMst generated by hbm2java
 */
@Entity
@Table(name = "PIC_BRANCH_MST")
public class PicBranchMst implements java.io.Serializable {

	private Long picBranchId;
	private String picBranchName;
	private String picBranchCode;
	private String picDivision;
	private String remarks;
	private Long userId;
	private Date dateTime;
	private Long prntCompyId;
	private String businessType;
	private String address;
	private List<LicOblApplicationMst> licOblApplicationMsts= new ArrayList<LicOblApplicationMst>();	
	private List<LicRequirementDtls> licRequirementDtlses = new ArrayList<LicRequirementDtls>();
	private List<LicPolicyMst> licPolicyMsts = new ArrayList<LicPolicyMst>();

	public PicBranchMst() {
	}

	public PicBranchMst(Long picBranchId) {
		this.picBranchId = picBranchId;
	}

	public PicBranchMst(Long picBranchId, String picBranchName,
			String picBranchCode, String picDivision, String remarks,
			Long userId, Date dateTime, Long prntCompyId,
			String businessType, String address) {
		this.picBranchId = picBranchId;
		this.picBranchName = picBranchName;
		this.picBranchCode = picBranchCode;
		this.picDivision = picDivision;
		this.remarks = remarks;
		this.userId = userId;
		this.dateTime = dateTime;
		this.prntCompyId = prntCompyId;
		this.businessType = businessType;
		this.address = address;
	}

	
	@Id
	@Column(name = "PIC_BRANCH_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getPicBranchId() {
		return this.picBranchId;
	}

	public void setPicBranchId(Long picBranchId) {
		this.picBranchId = picBranchId;
	}

	
	@Column(name = "PIC_BRANCH_NAME", length = 100)
	public String getPicBranchName() {
		return this.picBranchName;
	}

	public void setPicBranchName(String picBranchName) {
		this.picBranchName = picBranchName;
	}

	
	@Column(name = "PIC_BRANCH_CODE", length = 20)
	public String getPicBranchCode() {
		return this.picBranchCode;
	}

	public void setPicBranchCode(String picBranchCode) {
		this.picBranchCode = picBranchCode;
	}

	
	@Column(name = "PIC_DIVISION", length = 100)
	public String getPicDivision() {
		return this.picDivision;
	}

	public void setPicDivision(String picDivision) {
		this.picDivision = picDivision;
	}

	
	@Column(name = "REMARKS", length = 250)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	
	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	
	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	
	@Column(name = "PRNT_COMPY_ID", precision = 22, scale = 0)
	public Long getPrntCompyId() {
		return this.prntCompyId;
	}

	public void setPrntCompyId(Long prntCompyId) {
		this.prntCompyId = prntCompyId;
	}

	
	@Column(name = "BUSINESS_TYPE", length = 20)
	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	
	@Column(name = "ADDRESS", length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "picBranchMstId")
	public List<LicOblApplicationMst> getLicOblApplicationMsts() {
		return licOblApplicationMsts;
	}

	public void setLicOblApplicationMsts(
			List<LicOblApplicationMst> licOblApplicationMsts) {
		this.licOblApplicationMsts = licOblApplicationMsts;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "picBranchMst")
	public List<LicRequirementDtls> getLicRequirementDtlses() {
		return licRequirementDtlses;
	}

	public void setLicRequirementDtlses(
			List<LicRequirementDtls> licRequirementDtlses) {
		this.licRequirementDtlses = licRequirementDtlses;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "picBranchMst")
	public List<LicPolicyMst> getLicPolicyMsts() {
		return licPolicyMsts;
	}

	public void setLicPolicyMsts(List<LicPolicyMst> licPolicyMsts) {
		this.licPolicyMsts = licPolicyMsts;
	}

}
