package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RankMst generated by hbm2java
 */
@Entity
@Table(name = "RANK_MST")
public class RankMst implements java.io.Serializable {

	private Double rankId;
	private String rankDesig;
	private String qualNorms;
	private Long userId;
	private Date dateTime;
	private Set<AgentMst> agentMsts = new HashSet<AgentMst>(0);
	private Set<AgentRlns> agentRlnses = new HashSet<AgentRlns>(0);

	
	
	@Id
	@Column(name = "RANK_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Double getRankId() {
		return this.rankId;
	}

	public void setRankId(Double rankId) {
		this.rankId = rankId;
	}

	@Column(name = "RANK_DESIG", nullable = false, length = 50)
	public String getRankDesig() {
		return this.rankDesig;
	}

	public void setRankDesig(String rankDesig) {
		this.rankDesig = rankDesig;
	}

	@Column(name = "QUAL_NORMS", length = 350)
	public String getQualNorms() {
		return this.qualNorms;
	}

	public void setQualNorms(String qualNorms) {
		this.qualNorms = qualNorms;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rankMst")
	public Set<AgentMst> getAgentMsts() {
		return this.agentMsts;
	}

	public void setAgentMsts(Set<AgentMst> agentMsts) {
		this.agentMsts = agentMsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rankMst")
	public Set<AgentRlns> getAgentRlnses() {
		return this.agentRlnses;
	}

	public void setAgentRlnses(Set<AgentRlns> agentRlnses) {
		this.agentRlnses = agentRlnses;
	}

}
