package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RegionMst generated by hbm2java
 */
@Entity
@Table(name = "REGION_MST")
public class RegionMst implements java.io.Serializable {

	private Long regionId;
	private StateMst stateMst;
	private RegionMst regionMst;
	private String regionName;
	private String regionAbbr;
	private String regCode;
	private String addr1;
	private String addr2;
	private String addr3;
	private String city;
	private Long pin;
	private String phone;
	private String mobile;
	private String email;
	private String activeFlag;
	private String remarks;
	private Long userId;
	private Date dateTime;
	private Set<RegionMst> regionMsts = new HashSet<RegionMst>(0);
	private Set<UserMst> userMsts = new HashSet<UserMst>(0);
	private Set<DivisionMst> divisionMstsForPrntRegIdBns = new HashSet<DivisionMst>(0);
	private Set<DivisionMst> divisionMstsForPrntRegIdOps = new HashSet<DivisionMst>(0);

	public RegionMst() {
	}

	public RegionMst(Long regionId) {
		this.regionId = regionId;
	}

	public RegionMst(Long regionId, StateMst stateMst,
			RegionMst regionMst, String regionName, String regionAbbr,
			String regCode, String addr1, String addr2, String addr3,
			String city, Long pin, String phone, String mobile,
			String email, String activeFlag, String remarks, Long userId,
			Date dateTime, Set<RegionMst> regionMsts,
			Set<UserMst> userMsts,
			Set<DivisionMst> divisionMstsForPrntRegIdBns,
			Set<DivisionMst> divisionMstsForPrntRegIdOps) {
		this.regionId = regionId;
		this.stateMst = stateMst;
		this.regionMst = regionMst;
		this.regionName = regionName;
		this.regionAbbr = regionAbbr;
		this.regCode = regCode;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.addr3 = addr3;
		this.city = city;
		this.pin = pin;
		this.phone = phone;
		this.mobile = mobile;
		this.email = email;
		this.activeFlag = activeFlag;
		this.remarks = remarks;
		this.userId = userId;
		this.dateTime = dateTime;
		this.regionMsts = regionMsts;
		this.userMsts = userMsts;
		this.divisionMstsForPrntRegIdBns = divisionMstsForPrntRegIdBns;
		this.divisionMstsForPrntRegIdOps = divisionMstsForPrntRegIdOps;
	}

	@Id
	@Column(name = "REGION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Long regionId) {
		this.regionId = regionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_ID")
	public StateMst getStateMst() {
		return this.stateMst;
	}

	public void setStateMst(StateMst stateMst) {
		this.stateMst = stateMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRNF_LOC")
	public RegionMst getRegionMst() {
		return this.regionMst;
	}

	public void setRegionMst(RegionMst regionMst) {
		this.regionMst = regionMst;
	}

	@Column(name = "REGION_NAME", length = 25)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@Column(name = "REGION_ABBR", length = 3)
	public String getRegionAbbr() {
		return this.regionAbbr;
	}

	public void setRegionAbbr(String regionAbbr) {
		this.regionAbbr = regionAbbr;
	}

	@Column(name = "REG_CODE", length = 15)
	public String getRegCode() {
		return this.regCode;
	}

	public void setRegCode(String regCode) {
		this.regCode = regCode;
	}

	@Column(name = "ADDR_1", length = 250)
	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	@Column(name = "ADDR_2", length = 30)
	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "ADDR_3", length = 30)
	public String getAddr3() {
		return this.addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	@Column(name = "CITY", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "PIN", precision = 22, scale = 0)
	public Long getPin() {
		return this.pin;
	}

	public void setPin(Long pin) {
		this.pin = pin;
	}

	@Column(name = "PHONE", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "MOBILE", length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "EMAIL", length = 25)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ACTIVE_FLAG", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "REMARKS", length = 20)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regionMst")
	public Set<RegionMst> getRegionMsts() {
		return this.regionMsts;
	}

	public void setRegionMsts(Set<RegionMst> regionMsts) {
		this.regionMsts = regionMsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regionMst")
	public Set<UserMst> getUserMsts() {
		return this.userMsts;
	}

	public void setUserMsts(Set<UserMst> userMsts) {
		this.userMsts = userMsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regionMstByPrntRegIdBns")
	public Set<DivisionMst> getDivisionMstsForPrntRegIdBns() {
		return this.divisionMstsForPrntRegIdBns;
	}

	public void setDivisionMstsForPrntRegIdBns(
			Set<DivisionMst> divisionMstsForPrntRegIdBns) {
		this.divisionMstsForPrntRegIdBns = divisionMstsForPrntRegIdBns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regionMstByPrntRegIdOps")
	public Set<DivisionMst> getDivisionMstsForPrntRegIdOps() {
		return this.divisionMstsForPrntRegIdOps;
	}

	public void setDivisionMstsForPrntRegIdOps(
			Set<DivisionMst> divisionMstsForPrntRegIdOps) {
		this.divisionMstsForPrntRegIdOps = divisionMstsForPrntRegIdOps;
	}

}
