package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RoleMst generated by hbm2java
 */
@Entity
@Table(name = "ROLE_MST")
public class RoleMst implements java.io.Serializable {

	private Long roleId;
	private String roleName;
	private String activeFlag;
	private Long userId;
	private Date dateTime;
	private Set<UserRoleRlns> userRoleRlnses = new HashSet<UserRoleRlns>(0);
	private Set<RoleAccessRlns> roleAccessRlnses = new HashSet<RoleAccessRlns>(0);

	public RoleMst() {
	}

	public RoleMst(Long roleId, String roleName, String activeFlag) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.activeFlag = activeFlag;
	}

	public RoleMst(Long roleId, String roleName, String activeFlag,
			Long userId, Date dateTime,
			Set<UserRoleRlns> userRoleRlnses,
			Set<RoleAccessRlns> roleAccessRlnses) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.activeFlag = activeFlag;
		this.userId = userId;
		this.dateTime = dateTime;
		this.userRoleRlnses = userRoleRlnses;
		this.roleAccessRlnses = roleAccessRlnses;
	}

	@Id
	@SequenceGenerator(name="ROLE_MST_SEQ",sequenceName="ROLE_MST_SEQ")
	@GeneratedValue(generator="ROLE_MST_SEQ",strategy=GenerationType.AUTO)
	@Column(name = "ROLE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "ROLE_NAME", nullable = false, length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "ACTIVE_FLAG", nullable = false, length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleMst")
	public Set<UserRoleRlns> getUserRoleRlnses() {
		return this.userRoleRlnses;
	}

	public void setUserRoleRlnses(Set<UserRoleRlns> userRoleRlnses) {
		this.userRoleRlnses = userRoleRlnses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleMst")
	public Set<RoleAccessRlns> getRoleAccessRlnses() {
		return this.roleAccessRlnses;
	}

	public void setRoleAccessRlnses(Set<RoleAccessRlns> roleAccessRlnses) {
		this.roleAccessRlnses = roleAccessRlnses;
	}

}
