package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SchemeMst generated by hbm2java
 */
@Entity
@Table(name = "SCHEME_MST")
public class SchemeMst implements java.io.Serializable {

	private Long schId;
	private String schemeName;
	private String activeFlag;
	private Long userId;
	private Date dateTime;
	private Set<JoinProdMst> joinProdMsts = new HashSet<JoinProdMst>(0);
	private List<LicProductValueMst> licProductValueMsts = new ArrayList<LicProductValueMst>();
	private List<LicCollBenPctMst> licCollBenPctMsts = new ArrayList<LicCollBenPctMst>();

	public SchemeMst() {
	}

	public SchemeMst(Long schId) {
		this.schId = schId;
	}

	@Id
	@Column(name = "SCH_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getSchId() {
		return this.schId;
	}

	public void setSchId(Long schId) {
		this.schId = schId;
	}

	@Column(name = "SCHEME_NAME", length = 20)
	public String getSchemeName() {
		return this.schemeName;
	}

	public void setSchemeName(String schemeName) {
		this.schemeName = schemeName;
	}

	@Column(name = "ACTIVE_FLAG", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schemeMst")
	public Set<JoinProdMst> getJoinProdMsts() {
		return this.joinProdMsts;
	}

	public void setJoinProdMsts(Set<JoinProdMst> joinProdMsts) {
		this.joinProdMsts = joinProdMsts;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schemeMst")
	public List<LicProductValueMst> getLicProductValueMsts() {
		return licProductValueMsts;
	}

	public void setLicProductValueMsts(List<LicProductValueMst> licProductValueMsts) {
		this.licProductValueMsts = licProductValueMsts;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schemeMst")
	public List<LicCollBenPctMst> getLicCollBenPctMsts() {
		return licCollBenPctMsts;
	}

	public void setLicCollBenPctMsts(List<LicCollBenPctMst> licCollBenPctMsts) {
		this.licCollBenPctMsts = licCollBenPctMsts;
	}

}
