package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TieupCompyMst generated by hbm2java
 */
@Entity
@Table(name = "TIEUP_COMPY_MST")
public class TieupCompyMst implements java.io.Serializable {

	private Long tieCompyId;
	private String tieCompyName;
	private String tieupAbbr;
	private String addr;
	private Long pin;
	private String phone;
	private String mobile;
	private String email;
	private String activeFlag;
	private Long userId;
	private Date dateTime;
	private String corpLicns;
	private Set<LicOblApplicationMst> licOblApplicationMsts = new HashSet<LicOblApplicationMst>(0);
	private Set<UserMst> userMsts = new HashSet<UserMst>(0);

	private Set<JoinProdMst> joinProdMsts = new HashSet<JoinProdMst>(0);
	private Set<LicPaymentDtls>  licPaymentDtlses= new HashSet<LicPaymentDtls>(0);
	
	private List<PrintRcptMst> printRcptMsts = new ArrayList<PrintRcptMst>();
	private List<LicProductValueMst> licProductValueMsts = new ArrayList<LicProductValueMst>();
	private List<LicCollBenPctMst> licCollBenPctMsts = new ArrayList<LicCollBenPctMst>();
	
	private List<LicRnlPaymentDtls> licRnlPaymentDtlses = new ArrayList<LicRnlPaymentDtls>();
	private List<GenericBusinessTxn> genericBusinessTxns = new ArrayList<GenericBusinessTxn>();
	
	
	public TieupCompyMst() {
	}

	public TieupCompyMst(Long tieCompyId) {
		this.tieCompyId = tieCompyId;
	}

	
	@Id
	@Column(name = "TIE_COMPY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getTieCompyId() {
		return this.tieCompyId;
	}

	public void setTieCompyId(Long tieCompyId) {
		this.tieCompyId = tieCompyId;
	}

	
	@Column(name = "TIE_COMPY_NAME", length = 50)
	public String getTieCompyName() {
		return this.tieCompyName;
	}

	public void setTieCompyName(String tieCompyName) {
		this.tieCompyName = tieCompyName;
	}

	
	@Column(name = "TIEUP_ABBR", length = 5)
	public String getTieupAbbr() {
		return this.tieupAbbr;
	}

	public void setTieupAbbr(String tieupAbbr) {
		this.tieupAbbr = tieupAbbr;
	}

	
	@Column(name = "ADDR", length = 50)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	
	@Column(name = "PIN", precision = 22, scale = 0)
	public Long getPin() {
		return this.pin;
	}

	public void setPin(Long pin) {
		this.pin = pin;
	}

	
	@Column(name = "PHONE", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	
	@Column(name = "MOBILE", length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	
	@Column(name = "EMAIL", length = 25)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	
	@Column(name = "ACTIVE_FLAG", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	
	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	
	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	
	@Column(name = "CORP_LICNS", length = 20)
	public String getCorpLicns() {
		return this.corpLicns;
	}

	public void setCorpLicns(String corpLicns) {
		this.corpLicns = corpLicns;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tieupCompyMst")
	public Set<LicOblApplicationMst> getLicOblApplicationMsts() {
		return this.licOblApplicationMsts;
	}

	public void setLicOblApplicationMsts(
			Set<LicOblApplicationMst> licOblApplicationMsts) {
		this.licOblApplicationMsts = licOblApplicationMsts;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tieupCompyMst")
	public Set<UserMst> getUserMsts() {
		return this.userMsts;
	}

	public void setUserMsts(Set<UserMst> userMsts) {
		this.userMsts = userMsts;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tieupCompyMst")
	public Set<JoinProdMst> getJoinProdMsts() {
		return this.joinProdMsts;
	}

	public void setJoinProdMsts(Set<JoinProdMst> joinProdMsts) {
		this.joinProdMsts = joinProdMsts;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tieupCompyMst")
	public Set<LicPaymentDtls> getLicPaymentDtlses() {
		return licPaymentDtlses;
	}

	public void setLicPaymentDtlses(Set<LicPaymentDtls> licPaymentDtlses) {
		this.licPaymentDtlses = licPaymentDtlses;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tieupCompyMst")
	public List<PrintRcptMst> getPrintRcptMsts() {
		return printRcptMsts;
	}

	public void setPrintRcptMsts(List<PrintRcptMst> printRcptMsts) {
		this.printRcptMsts = printRcptMsts;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tieupCompyMst")
	public List<LicProductValueMst> getLicProductValueMsts() {
		return licProductValueMsts;
	}

	public void setLicProductValueMsts(List<LicProductValueMst> licProductValueMsts) {
		this.licProductValueMsts = licProductValueMsts;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tieupCompyMst")
	public List<LicCollBenPctMst> getLicCollBenPctMsts() {
		return licCollBenPctMsts;
	}

	public void setLicCollBenPctMsts(List<LicCollBenPctMst> licCollBenPctMsts) {
		this.licCollBenPctMsts = licCollBenPctMsts;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tieupCompyMst")
	public List<LicRnlPaymentDtls> getLicRnlPaymentDtlses() {
		return licRnlPaymentDtlses;
	}

	public void setLicRnlPaymentDtlses(List<LicRnlPaymentDtls> licRnlPaymentDtlses) {
		this.licRnlPaymentDtlses = licRnlPaymentDtlses;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tieupCompyMst")
	public List<GenericBusinessTxn> getGenericBusinessTxns() {
		return genericBusinessTxns;
	}

	public void setGenericBusinessTxns(List<GenericBusinessTxn> genericBusinessTxns) {
		this.genericBusinessTxns = genericBusinessTxns;
	}

	@Override
	public boolean equals(Object obj) {
		return this.getTieCompyId().equals(((TieupCompyMst) obj).getTieCompyId());
	}
	
}
