package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * UserRoleRlns generated by hbm2java
 */
@Entity
@Table(name = "USER_ROLE_RLNS")
public class UserRoleRlns implements java.io.Serializable {

	private Long id;
	private RoleMst roleMst;
	private UserMst userMst;
	private String activeFlag;
	private Long userId;
	private Date dateTime;

	public UserRoleRlns() {
	}

	public UserRoleRlns(Long id, RoleMst roleMst, UserMst userMst,
			String activeFlag) {
		this.id = id;
		this.roleMst = roleMst;
		this.userMst = userMst;
		this.activeFlag = activeFlag;
	}

	public UserRoleRlns(Long id, RoleMst roleMst, UserMst userMst,
			String activeFlag, Long userId, Date dateTime) {
		this.id = id;
		this.roleMst = roleMst;
		this.userMst = userMst;
		this.activeFlag = activeFlag;
		this.userId = userId;
		this.dateTime = dateTime;
	}

	@Id
	@SequenceGenerator(name="USER_ROLE_RLNS_SEQ",sequenceName="USER_ROLE_RLNS_SEQ")
	@GeneratedValue(generator="USER_ROLE_RLNS_SEQ",strategy=GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID", nullable = false)
	public RoleMst getRoleMst() {
		return this.roleMst;
	}

	public void setRoleMst(RoleMst roleMst) {
		this.roleMst = roleMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERID", nullable = false)
	public UserMst getUserMst() {
		return this.userMst;
	}

	public void setUserMst(UserMst userMst) {
		this.userMst = userMst;
	}

	@Column(name = "ACTIVE_FLAG", nullable = false, length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
