package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * UserLoginDtls generated by hbm2java
 */
@Entity
@Table(name = "USER_LOGIN_DTLS")
public class UserLoginDtls implements java.io.Serializable {

	private Long id;
	private Long userid;
	private Date loginTime;
	private Long branchId;

	public UserLoginDtls() {
	}

	public UserLoginDtls(Long id, Long userid,
			Date loginTime) {
		this.id = id;
		this.userid = userid;
		this.loginTime = loginTime;
	}

	public UserLoginDtls(Long id, Long userid,
			Date loginTime, Long branchId) {
		this.id = id;
		this.userid = userid;
		this.loginTime = loginTime;
		this.branchId = branchId;
	}

	@Id
	@SequenceGenerator(name="USER_LOGIN_DTLS_SEQ",sequenceName="USER_LOGIN_DTLS_SEQ")
	@GeneratedValue(generator="USER_LOGIN_DTLS_SEQ",strategy=GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "USERID", nullable = false, precision = 22, scale = 0)
	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	@Column(name = "LOGIN_TIME", nullable = false)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Column(name = "BRANCH_ID", precision = 22, scale = 0)
	public Long getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Long branchId) {
		this.branchId = branchId;
	}

}
