package com.gtfs.bean;

// Generated 30 Aug, 2014 4:24:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserMst generated by hbm2java
 */
@Entity
@Table(name = "USER_MST", uniqueConstraints = @UniqueConstraint(columnNames = "LOGIN"))
public class UserMst implements java.io.Serializable {

	private Long userid;
	private UserMst userMst;
	private RegionMst regionMst;
	private TieupCompyMst tieupCompyMst;
	private DivisionMst divisionMst;
	private BranchMst branchMst;
	private DesignationMst designationMst;
	private HoMst hoMst;
	private String userName;
	private String login;
	private String passwd;
	private String activeFlag;
	private Date lastLogin;
	private String remarks;
	private Long userId;
	private Date dateTime;
	private String superUserFlag;
	private String dept;
	private Set<UserMst> userMsts = new HashSet<UserMst>(0);
	private Set<UserRoleRlns> userRoleRlnses = new HashSet<UserRoleRlns>(0);
	
	private List<LicBrnhHubPicPodDtls> licBrnhHubPicPodDtlses = new ArrayList<LicBrnhHubPicPodDtls>();
	
	
	public UserMst() {
	}

	public UserMst(Long userid, DesignationMst designationMst,
			String userName, String login, String passwd) {
		this.userid = userid;
		this.designationMst = designationMst;
		this.userName = userName;
		this.login = login;
		this.passwd = passwd;
	}

	

	@Id
	@Column(name = "USERID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUPVSR_ID")
	public UserMst getUserMst() {
		return this.userMst;
	}

	public void setUserMst(UserMst userMst) {
		this.userMst = userMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGION_ID")
	public RegionMst getRegionMst() {
		return this.regionMst;
	}

	public void setRegionMst(RegionMst regionMst) {
		this.regionMst = regionMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIE_COMPY_ID")
	public TieupCompyMst getTieupCompyMst() {
		return this.tieupCompyMst;
	}

	public void setTieupCompyMst(TieupCompyMst tieupCompyMst) {
		this.tieupCompyMst = tieupCompyMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIV_ID")
	public DivisionMst getDivisionMst() {
		return this.divisionMst;
	}

	public void setDivisionMst(DivisionMst divisionMst) {
		this.divisionMst = divisionMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BRANCH_ID")
	public BranchMst getBranchMst() {
		return this.branchMst;
	}

	public void setBranchMst(BranchMst branchMst) {
		this.branchMst = branchMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DESIG_ID", nullable = false)
	public DesignationMst getDesignationMst() {
		return this.designationMst;
	}

	public void setDesignationMst(DesignationMst designationMst) {
		this.designationMst = designationMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HO_ID")
	public HoMst getHoMst() {
		return this.hoMst;
	}

	public void setHoMst(HoMst hoMst) {
		this.hoMst = hoMst;
	}

	@Column(name = "USER_NAME", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "LOGIN", unique = true, nullable = false, length = 20)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSWD", nullable = false, length = 50)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "ACTIVE_FLAG", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_LOGIN", length = 7)
	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Column(name = "REMARKS", length = 20)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "DATE_TIME")
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "SUPER_USER_FLAG", length = 1)
	public String getSuperUserFlag() {
		return this.superUserFlag;
	}

	public void setSuperUserFlag(String superUserFlag) {
		this.superUserFlag = superUserFlag;
	}

	@Column(name = "DEPT", length = 20)
	public String getDept() {
		return this.dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userMst")
	public Set<UserMst> getUserMsts() {
		return this.userMsts;
	}

	public void setUserMsts(Set<UserMst> userMsts) {
		this.userMsts = userMsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userMst")
	public Set<UserRoleRlns> getUserRoleRlnses() {
		return this.userRoleRlnses;
	}

	public void setUserRoleRlnses(Set<UserRoleRlns> userRoleRlnses) {
		this.userRoleRlnses = userRoleRlnses;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public List<LicBrnhHubPicPodDtls> getLicBrnhHubPicPodDtlses() {
		return licBrnhHubPicPodDtlses;
	}

	public void setLicBrnhHubPicPodDtlses(
			List<LicBrnhHubPicPodDtls> licBrnhHubPicPodDtlses) {
		this.licBrnhHubPicPodDtlses = licBrnhHubPicPodDtlses;
	}
}
